// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix0;
import 'package:robot_manager/data/mission.dart' as prefix1;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'Mission',
            r'.Mission',
            7,
            0,
            const prefix0.JsonSerializable(),
            const <int>[0, 1, 2, 7],
            const <int>[8, 9, 10, 11, 12, 2, 3, 4, 5, 6],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => (name) => b ? prefix1.Mission(name) : null},
            -1,
            0,
            const <int>[],
            const <Object>[prefix0.jsonSerializable],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r'name',
            32773,
            0,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const <Object>[const prefix0.JsonProperty(name: 'name')]),
        r.VariableMirrorImpl(
            r'tasks',
            2129925,
            0,
            const prefix0.JsonSerializable(),
            -1,
            2,
            3,
            const <int>[4],
            const <Object>[const prefix0.JsonProperty(name: 'tasks')]),
        r.MethodMirrorImpl(r'run', 262146, 0, -1, 5, 5, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 0, 3),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 0, 4),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 1, 5),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 1, 6),
        r.MethodMirrorImpl(r'', 0, 0, -1, 0, 0, const <int>[], const <int>[0],
            const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'==', 131074, -1, -1, 6, 6, const <int>[],
            const <int>[3], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'toString', 131074, -1, -1, 1, 1, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            65538,
            -1,
            -1,
            -1,
            -1,
            const <int>[],
            const <int>[4],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 131075, -1, -1, 7, 7, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'runtimeType', 131075, -1, -1, 8, 8, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'name',
            33798,
            7,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_name',
            32870,
            4,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_tasks',
            2130022,
            6,
            const prefix0.JsonSerializable(),
            -1,
            2,
            3,
            const <int>[4],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            32774,
            8,
            const prefix0.JsonSerializable(),
            -1,
            9,
            9,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            10,
            const prefix0.JsonSerializable(),
            -1,
            10,
            10,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.Mission,
        String,
        const m.TypeValue<List<prefix1.Task>>().type,
        List,
        prefix1.Task,
        const m.TypeValue<void>().type,
        bool,
        int,
        Type,
        Object,
        Invocation
      ],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'run': (dynamic instance) => instance.run,
        r'name': (dynamic instance) => instance.name,
        r'tasks': (dynamic instance) => instance.tasks
      },
      {
        r'name=': (dynamic instance, value) => instance.name = value,
        r'tasks=': (dynamic instance, value) => instance.tasks = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
